name: telepathy_admin
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  provider: ^6.0.3
  go_router: ^10.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  pointer_interceptor: ^0.10.1
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  awesome_dialog: ^3.2.0
    
  cupertino_icons: ^1.0.6

dependency_overrides:    
  intl: ^0.19.0
  ffi: ^2.0.1
  flutter_form_builder: ^7.2.1
  form_builder_validators: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_intl:
  enabled: true
  class_name: Lang
  main_locale: en